services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    command: start --user root --pass root --log info surrealkv:/data/srdb.db
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    restart: unless-stopped
